# <center><u>Numpy</u></center>

# Numpy Basics
Welcome to section of Numpy. This is the one of the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays.

NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 # Why Numpy?
 convenience & speed
 
Numpy is much faster than the standard python ways to do computations.
 
Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
 NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

## 1. Variable Declarartion

Reference:-https://www.youtube.com/watch?v=Y_nVWb9bcHY

<p style='text-align: right;'> 5 points</p>

In [2]:
# Import numpy using alias np

import numpy as np

In [ ]:
# create a numpy array 'a' with elements 1,2,3
# create a two dimensional array 'b' with elements(1,2,3) and (4,5,6)
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
# print the values of a and b
print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


Print shape of both a and b

In [ ]:
# your code here
print(a.shape)
print(b.shape)


(3,)
(2, 3)


Print the data types of a and b

In [ ]:
print(a.dtype)
print(b.dtype)

int64
int64


## 2. Add, remove elements and Memory Sharing

Reference:- https://www.youtube.com/watch?v=dEnCfapUbEw<br>
            https://www.youtube.com/watch?v=17vysCjwjxc

<p style='text-align: right;'> 10 points</p>


Declare x = np.array([ 5,10, 20, 12, 3])

In [ ]:
# declare x 
x = np.array([ 5,10, 20, 12, 3])


Add a new element 1 at the end of x

In [ ]:
# your code here
x = np.append(x,[1])

print(x) # check if 1 is added

[ 5 10 20 12  3  1]


Delete the second element of x 


In [ ]:
# your code here 
x = np.delete(x,1)
print(x) # check if the second element has been deleted

[ 5 20 12  3  1]


Set y = x


In [ ]:
y = x

Set the first element y =  1


In [ ]:
y[0] = 1
print(y)

[ 1 20 12  3  1]


Print x and y



In [ ]:
print(x)
print(y)


[ 1 20 12  3  1]
[ 1 20 12  3  1]


<b>you modified y, OMG!! but why x is also affected? Just give a try to answer this quest below </b>

In [ ]:
# write in commented form or markdown format

Set z = np.copy(x)


In [ ]:
z = np.copy(x)

Set the first element of y as 100


In [ ]:
y[0] = 100

print x and z to see if there is any change in x.

In [ ]:
print(x)
print(z)

[100  20  12   3   1]
[ 1 20 12  3  1]


<b>Hey the above output seems so interesting!!. When used copy function the changes did not affect on x. Can you Guess why ?<b>

In [ ]:
# write here - The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

## 4. Using various Numpy Functions.

Reference:- https://www.youtube.com/watch?v=HL-nfSG6F2I


<p style='text-align: right;'> 8*2 = 16 points</p>


Create a numpy array containing numbers from 1 to 12

In [ ]:
# x = #your code here 
x = np.array(range(1,13))
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Create a numpy array containing even numbers between 1 to 20




In [ ]:
y = np.array(range(1,21))
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Create an array of 2 rows and 2 columns containing all zeros.




In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

Create a matrix containing 3 rows and 2 columns where all the values are 1.




In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Create a matrix of size 5x5 where all are diagonal elements are 1, rest being 0.

In [ ]:
np.diag([1,1,1,1,1])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Create a matrix of size 4x2 where all the elements are 4




In [ ]:
All_fours = np.ones((4,2))*4
print(All_fours.astype(np.int32))

[[4 4]
 [4 4]
 [4 4]
 [4 4]]


Create a matrix where diagonal elements are [1 , 2, 3, 4, 5] and rest are zero




In [ ]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

Create a matrix of size 3x3 which contains random numbers from 0 to 1.




In [ ]:
np.random.rand(3,3)

array([[0.51089456, 0.64244511, 0.83868397],
       [0.49794751, 0.91875485, 0.73064323],
       [0.34697277, 0.70260078, 0.8100607 ]])

Create a numpy array of shape (50,) such that it contains evenly spaced numbers, from 1 to 20.

In [ ]:
np.linspace(1,20,50)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

## 5. Reshaping

Reference:-https://www.youtube.com/watch?v=sGCuryS8zjc

<p style='text-align: right;'> 4+1 = 5 points</p>


Use np.arange to create  a numpy array with values between 0 to 23

In [ ]:
a = np.arange(0,24)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
# print the shape of a
a.shape


(24,)

Using a suitable method, reshape a to have a dimension of (3,8). Print b and its shape


In [ ]:
b = a.reshape(3,8)
print(b)
print(b.shape)



[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
(3, 8)


Create another numpy array c  = a.reshape(2,-1)

In [ ]:
c = a.reshape(2,-1)

In [ ]:
#print c
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Print the shape of c.

In [ ]:
c.shape

(2, 12)

<b>Hey check above, what role -1 has played in reshape function. Don't worry</b>
<b> ok let me tell you this fun fact</b>

When using a -1, the dimension corresponding to the -1 will be the product of the dimensions of the original array divided by the product of the dimensions given to reshape so as to maintain the same number of elements

________

## 6. Accessing numpy arrays

Reference:-https://www.youtube.com/watch?v=y7kcnPy-NtQ


<p style='text-align: right;'> 6 points</p>


### Create an array, a = np.array([2,4,6,8,10,12,14,16])




In [3]:
a = np.array([2,4,6,8,10,12,14,16])

In [ ]:
# print a
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

<b>Using indexing and slicing, select the following mentioned subsets - </b>

In [5]:
# [4]
a[1]


4

In [8]:
a[1:6:2]

array([ 4,  8, 12])

In [9]:
#[4, 8, 12]
a[0:6:2]

array([ 2,  6, 10])

In [14]:
# [10, 12, 14, 16]
a[4:]

array([10, 12, 14, 16])

In [22]:
# [14, 16]
a[-3:]

array([12, 14, 16])

In [26]:
# [2, 6, 10, 14]
a[0:7:2]

array([ 2,  6, 10, 14])

## 7. Transposing

Reference:-https://www.youtube.com/watch?v=oNjX7nzFzrc

<p style='text-align: right;'> 4 points</p>


Create an array a = np.array([ [1, 2, 3], [4, 5, 6], [7,8,9], [10,11,12] ] )


In [27]:
a = np.array([ [1, 2, 3], [4, 5, 6], [7,8,9], [10,11,12] ] )

What is the shape of a?

In [28]:
a.shape

(4, 3)

### Create another array b which is transpose of a

In [34]:
b = a.transpose()

Print b and its shape

In [35]:
print(b)
print(b.shape)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
(3, 4)


## 8. Mathematical Operations

Reference:-https://www.youtube.com/watch?v=17vysCjwjxc

<p style='text-align: right;'> 8 points</p>


### Complete the following tasks given in comment using numpy function.

In [3]:
# complete your tasks here
import numpy as np
a = np.arange(10)
print(a)



[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Find sin value of a
np.sin(a)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [6]:
# Find cos value a
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [7]:
# Find exponential of all the values in a.

np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
# Find the sum of all the values in a.
np.sum(a, axis = None)


45

In [9]:
# Find the median value in a.
np.median(a)


4.5

In [10]:
#Find the max value of a
np.max(a)


9

In [11]:
#Find the min value of a
np.min(a)


0

In [19]:
# Find the index of the maximum element in a
np.where(a == np.max(a))


(array([9]),)

## 9. Hstack and vstack

Reference: https://www.youtube.com/watch?v=ksqPbrS-b78

<p style='text-align: right;'> 1 + 1 + 2 + 2 = 6 points</p>


Create a = np.array( [ [1, 2, 3], [ 4, 5, 6], [7 ,8, 9] ]) and print a.

In [22]:
a = np.array( [ [1, 2, 3], [ 4, 5, 6], [7 ,8, 9] ]) 
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Create b = np.array( [ [10, 11, 12] , [13,14,15], [16, 17, 18] ]) and print b


In [23]:
b = np.array( [ [10, 11, 12] , [13,14,15], [16, 17, 18] ]) 
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


Create a new array c stacking a and b horizontally, print the values and shape of this array.

In [24]:
c = np.hstack((a,b))
print(c.shape)
print(c)

(3, 6)
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


Create a new array d stacking a and b vertically, print the values and shape of this array.

In [26]:
d = np.vstack((a,b))
print(d)
print(d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)


____________

# Woohoo!!! you completed the 3rd milestone challenge too! Congratulations. 



____________

# FeedBack
We hope you’ve enjoyed this course so far. We’re committed to help you use "AI for All" course to its full potential, so that you have a great learning experience. And that’s why we need your help in form of a feedback here.

**Please fill this feedback form**
https://docs.google.com/forms/d/e/1FAIpQLSfjBmH0yJSSA34IhSVx4h2eDMgOAeG4Dk-yHid__NMTk3Hq5g/viewform