In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os

In C:\Users\adars_000\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\adars_000\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\adars_000\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\adars_000\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\adars_000\anaconda3\lib\site-packages\matplotlib\mpl-data\stylel

In [2]:
titanic_train = pd.read_csv("https://gist.githubusercontent.com/michhar/2dfd2de0d4f8727f873422c5d959fff5/raw/ff414a1bcfcba32481e4d4e8db578e55872a2ca1/titanic.csv",
                           sep='\t')   
titanic_train

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
151          152         1       1   
152          153         0       3   
153          154         0       3   
154          155         0       3   
155          156         0       1   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
152                                   Meo, Mr. Alfonzo    male  55.5      0   
153                    van Billiard, Mr. Austin Blyler    male  40.5      0   
154                              Olsen, Mr. Ole Martin    male   NaN      0   
155                        Williams, Mr. Charles Duane    male  51.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
151      0            113776  66.6000    C2        S  
152      0        A.5. 11206   8.0500   NaN        S  
153      2          A/5. 851  14.5000   NaN        S  
154      0         Fa 265302   7.3125   NaN        S  
155      1          PC 17597  61.3792   NaN        C  

[156 rows x 12 columns]

In [3]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [7]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked
count                      156   156     156    31      155
unique                     156     2     145    28        3
top     Moss, Mr. Albert Johan  male  113803   D26        S
freq                         1   100       2     2      110

In [13]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [14]:
titanic_train.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [20]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked
count                      156   156     156    31      155
unique                     156     2     145    28        3
top     Moss, Mr. Albert Johan  male  113803   D26        S
freq                         1   100       2     2      110

In [24]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [25]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [30]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[a].describe()

Name   Sex  Ticket Cabin Embarked
count                      156   156     156    31      155
unique                     156     2     145    28        3
top     Moss, Mr. Albert Johan  male  113803   D26        S
freq                         1   100       2     2      110

In [33]:
titanic_train[['Name','Sex','Age']].head(10)

Name     Sex   Age
0                            Braund, Mr. Owen Harris    male  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2                             Heikkinen, Miss. Laina  female  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4                           Allen, Mr. William Henry    male  35.0
5                                   Moran, Mr. James    male   NaN
6                            McCarthy, Mr. Timothy J    male  54.0
7                     Palsson, Master. Gosta Leonard    male   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0

In [44]:
#checking the first 15 sorted names
sorted(titanic_train['Name'])[5:15]

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Attalah, Miss. Malake',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
 'Barton, Mr. David John',
 'Bateman, Rev. Robert James',
 'Baxter, Mr. Quigg Edmond']

In [48]:
sorted(titanic_train["Name"])[5:12:2]

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andrew, Mr. Edgardo Samuel',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
 'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)']

In [ ]:
# sorted(titanic_train["Name"])  - gives all the names of the name column
# sorted(titanic_train["Name"])[5]  - gives top 5 names
# sorted(titanic_train["Name"])[5:10] - gives name from index 5 till 9
# sorted(titanic_train["Name"])[5:10:2] - gives name at the space of 2 from index 5 till 9

In [51]:
titanic_train["Ticket"][4:9]

4    373450
5    330877
6     17463
7    349909
8    347742
Name: Ticket, dtype: object

In [52]:
titanic_train["Ticket"].describe()

count        156
unique       145
top       113803
freq           2
Name: Ticket, dtype: object

In [53]:
titanic_train["adar"] = "raj"
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  
0      0         A/5 21171   7.2500   NaN        S  raj  
1      0          PC 17599  71.2833   C85        C  raj  
2      0  STON/O2. 3101282   7.9250   NaN        S  raj  
3      0            113803  53.1000  C123        S  raj  
4      0            373450   8.0500   NaN        S  raj

In [54]:
titanic_train["Cabin"].describe()

count      31
unique     28
top       D26
freq        2
Name: Cabin, dtype: object

In [55]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'adar'],
      dtype='object')

In [3]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [4]:
titanic_train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   156.000000  156.000000  156.000000  126.000000  156.000000   
mean     78.500000    0.346154    2.423077   28.141508    0.615385   
std      45.177428    0.477275    0.795459   14.613880    1.056235   
min       1.000000    0.000000    1.000000    0.830000    0.000000   
25%      39.750000    0.000000    2.000000   19.000000    0.000000   
50%      78.500000    0.000000    3.000000   26.000000    0.000000   
75%     117.250000    1.000000    3.000000   35.000000    1.000000   
max     156.000000    1.000000    3.000000   71.000000    5.000000   

            Parch        Fare  
count  156.000000  156.000000  
mean     0.397436   28.109587  
std      0.870146   39.401047  
min      0.000000    6.750000  
25%      0.000000    8.003150  
50%      0.000000   14.454200  
75%      0.000000   30.371850  
max      5.000000  263.000000

In [7]:
titanic_train.dtypes == "object"
a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
titanic_train[a].describe()

Name   Sex Ticket Cabin Embarked
count                      156   156    156    31      155
unique                     156     2    145    28        3
top     Celotti, Mr. Francesco  male  35281   D26        S
freq                         1   100      2     2      110

In [9]:
titanic_train["Name"][5:10]

5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [10]:
sorted(titanic_train["Name"])[5:10]

['Andersson, Mr. August Edvard ("Wennerstrom")',
 'Andreasson, Mr. Paul Edvin',
 'Andrew, Mr. Edgardo Samuel',
 'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
 'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)']

In [11]:
titanic_train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [12]:
titanic_train["adar"] = "raj"
titanic_train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked adar  
0      0  A/5 21171   7.2500   NaN        S  raj  
1      0   PC 17599  71.2833   C85        C  raj

In [19]:
#check the number of unique cabins
titanic_train["Cabin"].dtypes

dtype('O')

In [16]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
adar            object
dtype: object

In [20]:
titanic_train["Cabin"].describe()

count      31
unique     28
top       D26
freq        2
Name: Cabin, dtype: object

In [23]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])
new_Pclass

[3, 1, 3, 1, 3, ..., 1, 3, 3, 3, 1]
Length: 156
Categories (3, int64): [1, 2, 3]

In [22]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  
0      0         A/5 21171   7.2500   NaN        S  raj  
1      0          PC 17599  71.2833   C85        C  raj  
2      0  STON/O2. 3101282   7.9250   NaN        S  raj  
3      0            113803  53.1000  C123        S  raj  
4      0            373450   8.0500   NaN        S  raj

In [26]:
titanic_train["Cabin"].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2'], dtype=object)

In [37]:
import numpy as np
char_cabin = titanic_train["Cabin"].astype(str)

new_cabin = [cabin[0] for cabin in char_cabin]
new_cabin  = pd.Categorical(new_cabin)
new_cabin

['n', 'C', 'n', 'C', 'n', ..., 'C', 'n', 'n', 'n', 'n']
Length: 156
Categories (8, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'n']

In [38]:
titanic_train["Cabin"] = new_cabin
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  
0      0         A/5 21171   7.2500     n        S  raj  
1      0          PC 17599  71.2833     C        C  raj  
2      0  STON/O2. 3101282   7.9250     n        S  raj  
3      0            113803  53.1000     C        S  raj  
4      0            373450   8.0500     n        S  raj

In [39]:
titanic_train.dtypes

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex              object
Age             float64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin          category
Embarked         object
adar             object
dtype: object

In [40]:
titanic_train["Age"].isna().sum()

30

In [42]:
missing_Age = np.where(titanic_train["Age"].isnull() == True)
missing_Age

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [43]:
missing_Age = np.where(titanic_train["Age"].isnull() == True)
missing_Age

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [45]:
np.where(titanic_train["Fare"] == max(titanic_train["Fare"]))

(array([27, 88], dtype=int64),)

In [47]:
titanic_train.iloc[np.where(titanic_train["Fare"] == max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked adar  
27  19.0      3      2  19950  263.0     C        S  raj  
88  23.0      3      2  19950  263.0     C        S  raj

In [48]:
titanic_train.loc[np.where(titanic_train["Fare"] == max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked adar  
27  19.0      3      2  19950  263.0     C        S  raj  
88  23.0      3      2  19950  263.0     C        S  raj

In [49]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  
0      0         A/5 21171   7.2500     n        S  raj  
1      0          PC 17599  71.2833     C        C  raj  
2      0  STON/O2. 3101282   7.9250     n        S  raj  
3      0            113803  53.1000     C        S  raj  
4      0            373450   8.0500     n        S  raj

In [55]:
missing_age1 = np.where(titanic_train["Age"].isna() == True)
missing_age1

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [57]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  
0      0         A/5 21171   7.2500     n        S  raj  
1      0          PC 17599  71.2833     C        C  raj  
2      0  STON/O2. 3101282   7.9250     n        S  raj  
3      0            113803  53.1000     C        S  raj  
4      0            373450   8.0500     n        S  raj

In [72]:
sex_char2 = titanic_train["Sex"].astype(str)

new_sex = [sex_char2[0] for sex in sex_char2]
new_sex = pd.Categorical(new_sex)
new_sex

['male', 'male', 'male', 'male', 'male', ..., 'male', 'male', 'male', 'male', 'male']
Length: 156
Categories (1, object): ['male']

In [75]:
sex_char3 = titanic_train["Sex"].astype(str)
sex_char3
new_sex = [sex[0] for sex in sex_char3]
new_sex = pd.Categorical(new_sex)
new_sex

['m', 'f', 'f', 'f', 'm', ..., 'f', 'm', 'm', 'm', 'm']
Length: 156
Categories (2, object): ['f', 'm']

In [77]:
missing_age1 = np.where(titanic_train["Age"].isnull() == True)
missing_age1

(array([  5,  17,  19,  26,  28,  29,  31,  32,  36,  42,  45,  46,  47,
         48,  55,  64,  65,  76,  77,  82,  87,  95, 101, 107, 109, 121,
        126, 128, 140, 154], dtype=int64),)

In [86]:
titanic_train.loc[np.where(titanic_train["Age"].isnull() == True)].head()

PassengerId  Survived  Pclass                           Name     Sex  Age  \
5             6         0       3               Moran, Mr. James    male  NaN   
17           18         1       2   Williams, Mr. Charles Eugene    male  NaN   
19           20         1       3        Masselmani, Mrs. Fatima  female  NaN   
26           27         0       3        Emir, Mr. Farred Chehab    male  NaN   
28           29         1       3  O'Dwyer, Miss. Ellen "Nellie"  female  NaN   

    SibSp  Parch  Ticket     Fare Cabin Embarked adar  
5       0      0  330877   8.4583     n        Q  raj  
17      0      0  244373  13.0000     n        S  raj  
19      0      0    2649   7.2250     n        C  raj  
26      0      0    2631   7.2250     n        C  raj  
28      0      0  330959   7.8792     n        Q  raj

In [83]:
titanic_train.loc[np.where(titanic_train["Fare"] == max(titanic_train["Fare"]))]

PassengerId  Survived  Pclass                            Name     Sex  \
27           28         0       1  Fortune, Mr. Charles Alexander    male   
88           89         1       1      Fortune, Miss. Mabel Helen  female   

     Age  SibSp  Parch Ticket   Fare Cabin Embarked adar  
27  19.0      3      2  19950  263.0     C        S  raj  
88  23.0      3      2  19950  263.0     C        S  raj

In [87]:
# merge two columns

titanic_train[["SibSp","Parch"]].head()

SibSp  Parch
0      1      0
1      1      0
2      0      0
3      1      0
4      0      0

In [90]:
Family = titanic_train["SibSp"] + titanic_train["Parch"]
Family
titanic_train["Family"] = Family
titanic_train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked adar  Family  
0      0  A/5 21171   7.2500     n        S  raj       1  
1      0   PC 17599  71.2833     C        C  raj       1

In [93]:
titanic_train.iloc[np.where(titanic_train["Family"] == max(titanic_train["Family"]))]

PassengerId  Survived  Pclass                                Name     Sex  \
59           60         0       3  Goodwin, Master. William Frederick    male   
71           72         0       3          Goodwin, Miss. Lillian Amy  female   

     Age  SibSp  Parch   Ticket  Fare Cabin Embarked adar  Family  
59  11.0      5      2  CA 2144  46.9     n        S  raj       7  
71  16.0      5      2  CA 2144  46.9     n        S  raj       7

In [ ]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print("Dictionary:", d)
pd.Series(my_data, index=labels)

In [95]:
labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print(d)
print(my_data)

{'a': 10, 'b': 20, 'c': 30}
[10, 20, 30]


In [96]:
print(arr)

[10 20 30]


In [97]:
pd.Series(my_data, index = labels)

a    10
b    20
c    30
dtype: int64

In [100]:
pd.Series(arr)[1]

20

In [101]:
print(pd.Series(labels))

0    a
1    b
2    c
dtype: object


In [107]:
d = {'a':10, 'b':20, 'c':"khjk"}
pd.DataFrame(d, index = ['a','b','c'])

a   b     c
a  10  20  khjk
b  10  20  khjk
c  10  20  khjk

In [109]:
ser1 = pd.Series(['alpha','beta','gamma','delta'], index = [2,4,6,8])
ser1

2    alpha
4     beta
6    gamma
8    delta
dtype: object

In [110]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  Family  
0      0         A/5 21171   7.2500     n        S  raj       1  
1      0          PC 17599  71.2833     C        C  raj       1  
2      0  STON/O2. 3101282   7.9250     n        S  raj       0  
3      0            113803  53.1000     C        S  raj       1  
4      0            373450   8.0500     n        S  raj       0

In [111]:
ser1

2    alpha
4     beta
6    gamma
8    delta
dtype: object

In [112]:
ser2 = pd.Series([1,2,5,4],['CA','AB','BC','DE'])
ser2

CA    1
AB    2
BC    5
DE    4
dtype: int64

In [113]:
print(ser1)
print(ser2)

2    alpha
4     beta
6    gamma
8    delta
dtype: object
CA    1
AB    2
BC    5
DE    4
dtype: int64


In [114]:
ser3 = ser1 + ser2
ser3

2     NaN
4     NaN
6     NaN
8     NaN
AB    NaN
BC    NaN
CA    NaN
DE    NaN
dtype: object

In [119]:
ser1 = pd.Series([1,2,5,6],['AZ','BC','CD','DA'])
ser2 = pd.Series([1,3,4,5],['AB','BC','CD','DA'])
ser3 = ser1 + ser2
ser3

AB     NaN
AZ     NaN
BC     5.0
CD     9.0
DA    11.0
dtype: float64

In [150]:
# randomly assigning numbers

from numpy.random import randn as rn
matrix_data = rn(5,4)
row_labels = ('A','B','C','D','E')
column_headings = (1,2,3,4)

df = pd.DataFrame(matrix_data, row_labels, column_headings)
print(df)

          1         2         3         4
A  0.267016  0.688998  2.012252 -0.495160
B -1.584399 -2.367519  0.137036  1.124134
C -2.318685 -0.507900  2.210104 -0.915459
D  0.488059  0.482505 -0.627891  0.919784
E -0.244667  0.020375 -0.349989  1.503592


In [151]:
df.iloc[2]

1   -2.318685
2   -0.507900
3    2.210104
4   -0.915459
Name: C, dtype: float64

In [152]:
df[5] = df[1] + df[2]
df[5]

A    0.956014
B   -3.951918
C   -2.826585
D    0.970564
E   -0.224292
Name: 5, dtype: float64

In [153]:
print(df)

          1         2         3         4         5
A  0.267016  0.688998  2.012252 -0.495160  0.956014
B -1.584399 -2.367519  0.137036  1.124134 -3.951918
C -2.318685 -0.507900  2.210104 -0.915459 -2.826585
D  0.488059  0.482505 -0.627891  0.919784  0.970564
E -0.244667  0.020375 -0.349989  1.503592 -0.224292


In [154]:
titanic_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked adar  Family  
0      0         A/5 21171   7.2500     n        S  raj       1  
1      0          PC 17599  71.2833     C        C  raj       1  
2      0  STON/O2. 3101282   7.9250     n        S  raj       0  
3      0            113803  53.1000     C        S  raj       1  
4      0            373450   8.0500     n        S  raj       0

In [158]:
titanic_train = df.drop('adar')
titanic_train.head(2)

KeyError: "['adar'] not found in axis"

In [160]:
df1=df.drop('5')

KeyError: "['5'] not found in axis"

In [166]:
del df[5]
print(df)

          1         2         3         4
A  0.267016  0.688998  2.012252 -0.495160
B -1.584399 -2.367519  0.137036  1.124134
C -2.318685 -0.507900  2.210104 -0.915459
D  0.488059  0.482505 -0.627891  0.919784
E -0.244667  0.020375 -0.349989  1.503592


In [172]:
titanic_train.drop("adar",axis=1, inplace=True)
print(titanic_train.head(2))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  Family  
0      0  A/5 21171   7.2500     n        S       1  
1      0   PC 17599  71.2833     C        C       1  


In [174]:
titanic_train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  Family  
0      0  A/5 21171   7.2500     n        S       1  
1      0   PC 17599  71.2833     C        C       1

In [ ]:
#whenever you are using the drop command you should always use axis and inplace as well.
# whenver you are using del command to delete a column you can delete it by using only the column name.

In [175]:
print(df>0)

       1      2      3      4
A   True   True   True  False
B  False  False   True   True
C  False  False   True  False
D   True   True  False   True
E  False   True  False   True


In [178]:
print(df)

          1         2         3         4
A  0.267016  0.688998  2.012252 -0.495160
B -1.584399 -2.367519  0.137036  1.124134
C -2.318685 -0.507900  2.210104 -0.915459
D  0.488059  0.482505 -0.627891  0.919784
E -0.244667  0.020375 -0.349989  1.503592


In [184]:
df.loc[[1,2]]>0

KeyError: "None of [Int64Index([1, 2], dtype='int64')] are in the [index]"

In [186]:
from numpy.random import randn as rn
mat = rn(3,2)

row_l = ['A','B','C']
col_h = ['D','E']
df1 = pd.DataFrame(mat, row_l, col_h)
print(df1)

          D         E
A  0.967931 -0.000348
B  0.110071  1.483449
C -0.553329 -1.108325


In [191]:
df1.loc[['A','B']]>0

D      E
A  True  False
B  True   True

In [ ]:
#loc gets rows (or columns) with particular labels from the index. 
#iloc gets rows (or columns) at particular positions in the index (so it only takes integers).

In [195]:
df1.loc[['A']]

D         E
A  0.967931 -0.000348

In [199]:
df1.iloc[[1],[1]]

E
B  1.483449

In [200]:
df

1         2         3         4
A  0.267016  0.688998  2.012252 -0.495160
B -1.584399 -2.367519  0.137036  1.124134
C -2.318685 -0.507900  2.210104 -0.915459
D  0.488059  0.482505 -0.627891  0.919784
E -0.244667  0.020375 -0.349989  1.503592

In [201]:
df1

D         E
A  0.967931 -0.000348
B  0.110071  1.483449
C -0.553329 -1.108325

In [204]:
booldf1 = df1>0
print(df1[booldf1])

          D         E
A  0.967931       NaN
B  0.110071  1.483449
C       NaN       NaN


In [208]:
matrix_data = np.matrix('1,10,100; 2,20,200; 3,30,300; 4,40,400; 5,50,500')
row_l = ['A','B','C','D','E']
col_h = ['Section','Rank','Marks']
matrix_data

matrix([[  1,  10, 100],
        [  2,  20, 200],
        [  3,  30, 300],
        [  4,  40, 400],
        [  5,  50, 500]])

In [209]:
mat1 = pd.DataFrame(matrix_data,row_l,col_h)
print(mat1)

   Section  Rank  Marks
A        1    10    100
B        2    20    200
C        3    30    300
D        4    40    400
E        5    50    500


In [ ]:
df[df['Height']>65]

In [213]:
mat1[mat1['Section']>2]

Section  Rank  Marks
C        3    30    300
D        4    40    400
E        5    50    500

In [215]:
mat1[['Section','Rank']]

Section  Rank
A        1    10
B        2    20
C        3    30
D        4    40
E        5    50

In [216]:
boolmat1 = mat1['Section']>2
boolmat2 = mat1['Rank']>30

In [217]:
print(mat1[(boolmat1) & (boolmat2)])

   Section  Rank  Marks
D        4    40    400
E        5    50    500


In [218]:
print(mat1[boolmat1][['Rank','Marks']])

   Rank  Marks
C    30    300
D    40    400
E    50    500


In [219]:
titanic_train.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  Family  
0      0  A/5 21171   7.2500     n        S       1  
1      0   PC 17599  71.2833     C        C       1

In [224]:
titanic_train["Name"][0:6:2]

0     Braund, Mr. Owen Harris
2      Heikkinen, Miss. Laina
4    Allen, Mr. William Henry
Name: Name, dtype: object

In [227]:
sex_char = titanic_train["Sex"].astype(str)

new_sex = [sex[0] for sex in sex_char]
new_sex = pd.Categorical(new_sex)
new_sex

['m', 'f', 'f', 'f', 'm', ..., 'f', 'm', 'm', 'm', 'm']
Length: 156
Categories (2, object): ['f', 'm']

In [228]:
mat1

Section  Rank  Marks
A        1    10    100
B        2    20    200
C        3    30    300
D        4    40    400
E        5    50    500

In [230]:
mat1.reset_index()

index  Section  Rank  Marks
0     A        1    10    100
1     B        2    20    200
2     C        3    30    300
3     D        4    40    400
4     E        5    50    500

In [233]:
mat1.reset_index(drop = True)
"Engineer Doctor Teacher Student Fielder".split()

['Engineer', 'Doctor', 'Teacher', 'Student', 'Fielder']

In [234]:
mat1

Section  Rank  Marks
A        1    10    100
B        2    20    200
C        3    30    300
D        4    40    400
E        5    50    500

In [235]:
mat1["Profession"] = "Engineer Doctor Teacher Student Fielder".split()

In [236]:
mat1

Section  Rank  Marks Profession
A        1    10    100   Engineer
B        2    20    200     Doctor
C        3    30    300    Teacher
D        4    40    400    Student
E        5    50    500    Fielder

In [237]:
mat1.set_index("Profession")

Section  Rank  Marks
Profession                      
Engineer          1    10    100
Doctor            2    20    200
Teacher           3    30    300
Student           4    40    400
Fielder           5    50    500